name: DeluxeChat
main: me.clip.deluxechat.DeluxeChat
version: 1.9
author: extended_clip
description: Deluxe chat formatting system
softdepend: [AcidIsland, ASkyBlock, Autorank, AutoSell, BanManager, ChatColor, ChatReaction, CheckNameHistory, DeluxeTags, Essentials, EZBlocks, EZPrestige, EZRanksLite, EZRanksPro, Factions, GAListener, GangsPlus, Heroes, IslandWorld, Jobs, KillRewards, killStats, LWC, MarriageMaster, McInfected, McInfected-Ranks, mcMMO, MVdWPlaceholderAPI, Nicky, PlaceholderAPI, PlotMe, PlayerPoints, PlotMe, PlotSquared, PrisonGangs, pvpstats, QuickSell, RoyalCommands, SimpleClans, SimpleCoinsAPI, Simple Suffix, SkyWarsReloaded, SQLPerms, SQLTokens, SurvivalGames, Teams, TokenEnchant, Towny, TownyChat, uSkyBlock, UltimateVotes, Vault, VoteParty, Werewolf, WickedSkyWars]
permissions:
    chatformat.default:
        description: Standard chatformat
        default: true
    deluxechat.color:
        description: kan använda färgkoder i chatten
        default: op
    deluxechat.formatting:
        description: kan använda stilkoder i chatten
        default: op
    deluxechat.utf:
        description: kan använda speciella utf-koder i chatten
        default: op
    deluxechat.admin:
        description: kan använda dchat kommandon
        default: op
    deluxechat.filter.bypass:
        description: ignorerar chatfiltret om det är aktivt
        default: op
    deluxechat.url:
        description: kan skicka klickbara länkar i chatten
        default: op
    deluxechat.bungee.chat:
        description: kan chatta globalt om bungee är aktiverat
        default: op
    deluxechat.bungee.toggle:
        description: kan chatta globalt om bungee är aktiverat
        default: op
    deluxechat.bungee.override:
        description: skicka alltid till alla spelare när det är globalt chattmeddelande, även om spelaren själv kör med serverchatt
        default: op
    deluxechat.pm:
        description: kan skicka och besvara privata meddelanden med /msg or /reply
        default: op
    deluxechat.pm.color:
        description: kan använda färgkoder i privata meddelanden
        default: op
    deluxechat.pm.formatting:
        description: kan använda stilkoder i privata meddelanden
        default: op
    deluxechat.pm.url:
        description: kan skicka länkar i privata meddelanden
        default: op
    deluxechat.socialspy:
        description: kan spionera på privata meddelanden
        default: op
    deluxechat.socialspy.onjoin:
        description: sätter igång spionering på privata meddelanden vid inloggning
        default: op
commands:
   dchat:
     description: Chatpogrammets huvudkommando
     aliases: [deluxechat]
   gtoggle:
     description: Växlar globalt/bungeecord chatt på/av
     aliases: [globaltoggle]
   msg:
     description: Skicka ett privat meddelande till eb spelare
     aliases: [message, pm, tell, whisper, w, t, m]
   reply:
     description: Besvara ett privat meddelande
     aliases: [r]
   socialspy:
     description: spionera på privata meddelanden
     aliases: [deluxesocialspy]
