#=====================================================
#=              Acknowledge-Rules v 3.1              =
#=                    by Samuel98                    =
#=---------------------------------------------------=
#=                Plugin Configuration               =
#=                   bit.ly/1HAbNrj                  =
#=====================================================
#
CommandList:
  # 
  # The command name for the rules command.
  # Default is /rules. Make sure this is in lowercase.
  Rules: rules
  # 
  # The command name for the approve-rules command.
  # Default is /approverules. Make sure this is in lowercase.
  ApproveRules: approverules
  # 
  # The command name for the maintain-rules command.
  # Default is /maintainrules. Make sure this is in lowercase.
  MaintainRules: maintainrules
  # 
  # The command name for the ack-rules command.
  # Default is /ackrules. Make sure this is in lowercase.
  AckRules: ackrules
  # 
  # The command name for the rescind-rules command.
  # Default is /rescindrules. Make sure this is in lowercase.
  RescindRules: rescindrules
General:
  # 
  # Whether or not messages should be broadcast
  # to everyone on the server (with notify permission).
  Broadcast-Messages: true
  # 
  # Whether or not messages should be sent to
  # the sender of commands.
  Message-Senders: true
  # 
  # Whether or not the plugin should check for
  # updates when loaded.
  Check-For-Updates: true
  # 
  # Should players be teleported to a custom
  # location when they join (if they've not
  # previously acknowledged the rules).
  TP-On-Login: true
  # 
  # Should players be teleported to a custom
  # location once they've acknowledged the rules.
  TP-On-Approve: true
  # 
  # Should the rules be listed using numbers?
  Rules-Num-Prefix: false
  # 
  # Or should the rules be listed with bullet points?
  Rules-List-Prefix: true
  # 
  # Whether or not the stored rule sets (the sets
  # which each player has read) should be cleared on quit.
  Clear-Rule-Sets-On-Logoff: true
  # 
  # Whether or not to pick a random colour for the
  # interactive messages on each use.
  Randomly-Colour-Interactive-Messages: false
  # 
  # Whether or not each rule set should have a
  # cooldown between each use.
  RulesSetsCooldown: true
  # 
  # The time for the cooldown in seconds.
  # The default is set as 10 seconds.
  RulesSetsCooldownSeconds: 5
  # 
  # Whether or not there should be a cooldown
  # between each error message.
  ErrorMessageCooldown: true
  # 
  # The time for the cooldown in seconds.
  # The default is set as 30 seconds.
  ErrorMessageCooldownSeconds: 30
  # 
  # The time (in seconds) of which the
  # repeating acknowledge title message should
  # wait before firing up for the player on join.
  # The default is one second.
  Join-Message-Titles-Delay: 1
  # 
  # Whether or not the plugin should sent
  # basic info to mcstats.org.
  Enable-Metrics: false
  # 
  # Whether or not the commands provided below
  # should be run after acknowledging the rules.
  Run-Commands-After-Acknowledge: true
  # 
  # Whether or not rules messages should display
  # using interactive messages or standard messages.
  Enable-Interactive-Messages: true
BeforeAcknowledge:
  Build&Interact: false
  # 
  # Whether or not players which have not previously
  # acknowledged the rules should have the ability to move.
  Move: true
  # 
  # Whether or not players which have not previously
  # acknowledged the rules should have the ability to
  # use commands which are not specified below.
  Commands: false
  # 
  # Whether or not players which have not previously
  # acknowledged the rules should be able to
  # speak in the chat.
  Prevent-Chat: false
  # 
  # Whether or not players which have not previously
  # acknowledged the rules should be able to
  # see the that typed by others.
  Hide-Chat: false
  # 
  # Whether or not players which have not previously
  # acknowledged the rules should take damage.
  Injuries: false
  # 
  # Whether or not players which have not previously
  # acknowledged the rules should keep their inventories.
  Inventories: false
  # 
  # Whether or not players which have not previously
  # acknowledged the rules should have their
  # game-mode set to Adventure.
  Adventure-Mode: true
  # 
  # Whether or not players which have not previously
  # acknowledged the rules will be kicked after
  # 10 minutes of joining and not doing so.
  Kick-After-10-Minutes: true
  # 
  # Whether or not titles are sent to players
  # who have not previously acknowledged the rules on join.
  Join-Message-Titles: true
  # 
  # Whether or not a message is sent to players
  # who have not previously acknowledged the rules on join.
  Join-Repeating-Message: true
  # 
  # The frequency (seconds) of which the repeating
  # join message is displayed.
  Join-Repeating-Message-Time: 60
  # 
  # Whether or not players which have not previously
  # acknowledged the rules are able to interact
  # with blocks/items.
  Buid&Interact: false
# 
# A list of commands which can be executed before
# players have acknowledged the rules.
AllowedCommands:
- ackrules
- acknowledgerules
- maintainrules
- approverules
- rules
- help
- broadcast
# 
# A list of world names and gamemodes they should be using.
WorldModes:
  world: SURVIVAL
  world_nether: SURVIVAL
  world_the_end: SURVIVAL
  hub: ADVENTURE
# 
# The location that players are teleported to
# if they have not acknowledged before.
Locations:
  Login:
    World: world
    X: -32.56966734300822
    Y: 63.0
    Z: -101.18585384398104
    Pitch: 4.0500283
    Yaw: -1.0662334
  Approve:
    World: world
    X: -30.367459825660045
    Y: 79.0
    Z: -79.90585719871666
    Pitch: 7.8000345
    Yaw: -181.66602
# 
# A list of custom commands which will
# be run after a player acknowledges the
# rules, as long as they are enabled above.
AcknowledgeCommands:
- command_name argument1 argument2
- broadcast &displayname acknowledged rules.
