name: Craftconomy3
main: com.greatmancode.craftconomy3.tools.interfaces.BukkitLoader
version: 3.3-e72ac42-trv178
author: Greatman
commands:
    money:
      description: Check / Distribute currency.
    bank:
      description: Check / Distribute money on a Bank.
    craftconomy:
      description: Configuration command
    ccsetup:
      description: Setup command
    currency:
      description: Currency management command
    ccgroup:
      description: world group management command
    pay:
      description: /money pay shortcut
