language: en
allow-command-questing: true
allow-command-quests-with-npcs: false
show-requirements: true
allow-quitting: true
ignore-locked-quests: true
debug-mode: false
generate-files-on-join: true
kill-delay: 600
accept-timeout: 20
show-npc-effects: true
npc-effect: note
max-quests: 0
convert-data-on-startup: false
quester-blacklist:
- UUID
- UUID
- UUID
