name: AntiXRay
main: me.ryanhamshire.AntiXRay.AntiXRay
softdepend: [Multiverse-Core, My Worlds, Transporter]
version: 1.8.5
author: blablubbabc
authors: [bigscary, blablubbabc]
website: dev.bukkit.org/server-mods/anti-x-ray/
commands:
    antixray:
        description: Antixrays kommandon.
        usage: /<command>
        aliases: ['xray', 'ax']
permissions:
    antixray.bypass:
        description: Tillåter att spelaren hackar vilket block som helst utan begränsning.
        default: false
    antixray.reload:
        description: Låter spelaren ladda om konfigureringen.
        default: op
    antixray.check.others:
        description: Låter spelaren se en annan spelares återstående poäng innan gränsen är nådd.
        default: op
    antixray.check.self:
        description: Låter spelaren se sina åtestående poäng innan gränsen är nådd.
        default: op
    antixray.set:
        description: Tillåter att spelaren ställer in en annan spelares poäng, som t.ex. återstående gruvdrift.
        default: op
    antixray.monitorxrayers:
        description: Om konfigurerad, tillåter att spelaren blir underrättadom spelare som når deras gruvdriftsgräns.
        default: op
    antixray.help:
        description: Låter spelaren se hjälpavsnittet som visar det här tilläggets alla kommandon.
        default: op
