# ActionAnnouncer v1.9 Main configuration
deluxechat_placeholders: true
announcer_enabled: true
announcer_random: true
announce_interval: 140
announcement_length: 4
announcements:
- '&aBygg inte 150 block eller närmare andra spelare eller startstadens skydd!'
- '&bDet är just nu &e{onlineplayers} &bplayers online!'
- '&cFör nyttiga länkar så skriv &6/länkar &ci chatten!'
- '&4Tänk på att ha ett vårdat språk! Barn spelar också här!'
- '&cSkriv /hjälp för vägledning till vart den bästa hjälpen kan fås. :P'
announce_on_join: false
join_announcement: '&eVälkommen till servern &b%player%! Det finns &f%online% &espelare
  online just nu!'
disable_sounds: false
