name: ActionAnnouncer
main: me.clip.actionannouncer.ActionAnnouncer
version: 1.9
author: extended_clip
softdepend: [PlaceholderAPI]
description: Skickar meddelanden p책 actionraden!
permissions:
    actionannouncer.reload:
        description: laddar om till채ggets config
        default: op
    actionannouncer.send:
        description: skickar meddelande till en spelare
        default: op
    actionannouncer.announce:
        description: skickar meddelande till alla spelare
        default: op
    actionannouncer.list:
        description: visar lista med aktiva meddelanden
        default: op
    actionannouncer.add:
        description: l채gger till ett meddelande
        default: op
    actionannouncer.remove:
        description: tar bort ett meddelande
        default: op
    actionannouncer.start:
        description: startar automatiska meddelanden
        default: op
    actionannouncer.stop:
        description: stoppar automatiska meddelanden
        default: op
    actionannouncer.help:
        description: anv채nd aa help kommandot
        default: op
commands:
   actionannouncer:
     description: ActionAnnouncer kommando
     aliases: [aa]