#     ....    .   .   ....
#    .   .   .. ..   .   .
#   .   .   . . .   ....
#  .   .   .   .   .
# ....    .   .   .      
# DeathMessagesPrime Configuration File

# Configuration version, do not change this unless you want your config to be reset.
config-version: 4 

# World groups.
# If a world is in a group, and a death occurs there, the appropriate death message
# will be shown in rest of the worlds in that same group too.
# 
# If _enabled is false, this feature is disabled. Instead, the death message behavior
# will be specified with per-world-messages
world-groups:
  _enabled: true
  world:
    - world
    - world_nether
    - world_the_end
  
# List worlds, where death messages from PvP are not recorded, here.
worlds-no-pvp-death-messages:
# - world2

# List worlds, where death messages from anything else than PvP are not recorded, here.
worlds-no-natural-death-messages:
# - world2

# List worlds, where death messages are only shown to the killer and the victim, here.
worlds-private-pvp-death-messages:
# - world3

# List worlds, where death messages are only shown to the player that died here.
worlds-private-natural-death-messages:
# - world3

# Show debug information upon death, useful for determining plugin conflicts, etc.
debug: false

# Show death messages in all worlds, if false. Needs to be true in order to world
# groups to function.
per-world-messages: true

# Death message compatibility: set the message as normal, until HIGHEST,
# when it is emptied.
death-message-compat-mode: false

# Broadcast death message to console.
# none: Do not print death message in console.
# normal: Print the DeathMessagesPrime message in console.
# verbose: Print a verbose message, including coordinates, and other info.
# Verbose is useful for debugging
console-death-message: normal

# The priority for the listener. Set to lower value if there are any conflicts with
# plugins such as CrackShot.
# In order from higher to lower: HIGHEST, HIGH, NORMAL, LOW, LOWEST, MONITOR
death-listener-priority: HIGH

# Whether to show the custom weapon death messages (ZombieCustom for example)
# on all weapons (true), or only on weapons with custom names (false).
show-custom-death-msg-on-all-weapons: false

# Here are the actual death messages. They are as a list, so you can add as many as
# you want, and the plugin will support it. Color codes in format &0-&f and &k-&r are
# supported.
#
# %player% represents the player's name.
# %name% represents the player's display name.
# %killer% represents the killer player (in PvP reasons), or 
#          pursuing mob (in DrowningMob etc. reasons) (mob names can be changed in
#          mob-names section).
# %killer2% represents the killer player's display name in PvP reasons only.
# %weapon_name% represents the weapon name.
# %weapon% represents the weapon name (including the tooltip).
# %world% represents the world name of the death.
# %biome% represents the biome, where the death occurred. 
death-messages: 
  # Prefix of all death messages
  prefix: "&a[&eD&a] &c" 
  # Suffix of all death messages
  suffix: "" 
  mob:
    BlazeMelee:
      - "%player% was slain by Blaze"
    BlazeFireball:
      - "%player% was fireballed by Blaze"
    CaveSpider:
      - "%player% was slain by Cave Spider"
    Creeper:
      - "%player% was blown up by Creeper"
    ElderGuardian:
      - "%player% was slain by Elder Guardian"
    EnderDragon:
      - "%player% was slain by Ender Dragon"
    EnderDragonBreath:
      - "%player% was killed by Ender Dragon using magic"
    Enderman:
      - "%player% was slain by Enderman"
    Endermite:
      - "%player% was slain by Endermite"
    Ghast:
      - "%player% was fireballed by Ghast"
    Giant:
      - "%player% was slain by Giant"
    Guardian:
      - "%player% was slain by Guardian"
    IronGolem:
      - "%player% was slain by Iron Golem"
    MagmaCube:
      - "%player% was slain by Magma Cube"
    Rabbit:
      - "%player% was slain by The Killer Bunny"
    Shulker:
      - "%player% was slain by Shulker"
    Silverfish:
      - "%player% was slain by Silverfish"
    SkeletonArrow:
      - "%player% was shot by Skeleton"
    SkeletonMelee:
      - "%player% was slain by Skeleton"
    SkeletonCustom:
      - "%player% was slain by Skeleton using [%weapon_name%&f]"
      - "%player% got finished off by Skeleton using [%weapon_name%&f]"
    Slime:
      - "%player% was slain by Slime"
    SnowGolem:
      - "%player% was pummeled by Snow Golem"
    Spider:
      - "%player% was slain by Spider"
    Witch:
      - "%player% was killed by Witch using magic"
    Wither:
      - "%player% was slain by Wither"
    WitherSpawnBoom: # Dies from wither spawn explosion
      - "%player% was blown up by Wither"
    WitherSkeletonMelee:
      - "%player% was slain by Wither Skeleton"
    WitherSkeletonCustom:
      - "%player% was slain by Wither Skeleton using [%weapon_name%&f]"
      - "%player% got finished off by Wither Skeleton using [%weapon_name%&f]"
    Wolf:
      - "%player% was slain by Wolf"
    ZombieMelee:
      - "%player% was slain by Zombie"
    ZombieCustom:
      - "%player% was slain by Zombie using [%weapon_name%&f]"
      - "%player% got finished off by Zombie using [%weapon_name%&f]"
    ZombiePigManMelee:
      - "%player% was slain by Zombie Pigman"
    ZombiePigManCustom:
      - "%player% was slain by Zombie Pigman using [%weapon_name%&f]"
      - "%player% got finished off by Zombie Pigman using [%weapon_name%&f]"
  namedmob: # For named mobs, use %killer% as mob
    BlazeMelee:
      - "%player% was slain by %killer%"
    BlazeFireball:
      - "%player% was fireballed by %killer%"
    CaveSpider:
      - "%player% was slain by %killer%"
    Creeper:
      - "%player% was blown up by %killer%"
    ElderGuardian:
      - "%player% was slain by %killer%"
    EnderDragon:
      - "%player% was slain by %killer%"
    Enderman:
      - "%player% was slain by %killer%"
    Endermite:
      - "%player% was slain by %killer%"
    Ghast:
      - "%player% was fireballed by %killer%"
    Giant:
      - "%player% was slain by %killer%"
    Guardian:
      - "%player% was slain by %killer%"
    IronGolem:
      - "%player% was slain by %killer%"
    MagmaCube:
      - "%player% was slain by %killer%"
    Rabbit:
      - "%player% was slain by %killer%"
    Shulker:
      - "%player% was slain by %killer%"
    Silverfish:
      - "%player% was slain by %killer%"
    SkeletonArrow:
      - "%player% was shot by %killer%"
    SkeletonMelee:
      - "%player% was slain by %killer%"
    SkeletonCustom:
      - "%player% was slain by %killer% using [%weapon_name%&f]"
      - "%player% got finished off by %killer% using [%weapon_name%&f]"
    Slime:
      - "%player% was slain by %killer%"
    SnowGolem:
      - "%player% was pummeled by %killer%"
    Spider:
      - "%player% was slain by %killer%"
    Witch:
      - "%player% was killed by %killer% using magic"
    Wither:
      - "%player% was slain by %killer%"
    WitherSpawnBoom: # Dies from wither spawn explosion
      - "%player% was blown up by %killer%"
    WitherSkeletonMelee:
      - "%player% was slain by %killer%"
    WitherSkeletonCustom:
      - "%player% was slain by %killer% using [%weapon_name%&f]"
      - "%player% got finished off by %killer% using [%weapon_name%&f]"
    Wolf:
      - "%player% was slain by %killer%"
    ZombieMelee:
      - "%player% was slain by %killer%"
    ZombieCustom:
      - "%player% was slain by %killer% using [%weapon_name%&f]"
      - "%player% got finished off by %killer% using [%weapon_name%&f]"
    ZombiePigManMelee:
      - "%player% was slain by %killer%"
    ZombiePigManCustom:
      - "%player% was slain by %killer% using [%weapon_name%&f]"
      - "%player% got finished off by %killer% using [%weapon_name%&f]"
  pvp:
    PlayerMelee:
      - "%player% was slain by %killer%"
    PlayerCustom:
      - "%player% was slain by %killer% using [%weapon_name%&f]"
    PlayerArrow:
      - "%player% was shot by %killer%"
    PlayerFireball: # Just in case
      - "%player% was fireballed by %killer%"
    PlayerSnowball: # Just in case
      - "%player% was pummeled by %killer%"
    PlayerProjectileCustom: # This is in case of plugins like CrackShot
      - "%player% was shot by %killer% using [%weapon_name%&f]"
    PlayerPotion:
      - "%player% was killed by %killer% using magic"
  natural:
    Thorns:
      - "%player% was killed while trying to hurt %killer%"
    TNT:
      - "%player% blew up"
    TNTKill:
      - "%player% was blown up by %killer%"
    EnderCrystal:
      - "%player% blew up"
    Cactus:
      - "%player% was pricked to death"
    CactusKill:
      - "%player% walked into a cactus whilst trying to escape %killer%"
    Anvil:
      - "%player% was squashed by a falling anvil"
    FallingBlock: # Only when a FallingBlock is modified to cause damage
      - "%player% was squashed by a falling block"
    DispenserArrow:
      - "%player% was shot by arrow"
    DispenserFireball:
      - "%player% burned to death"
    DispenserSnowball:
      - "%player% died"
    Drowning:
      - "%player% drowned"
    DrowningKill:
      - "%player% drowned whilst trying to escape %killer%"
    PotionPoison: # Normally impossible
      - "%player% died"
    PotionWither:
      - "%player% withered away"
    PotionHarming:
      - "%player% was killed by magic"
    FireBlock:
      - "%player% went up in flames"
    FireBlockKill:
      - "%player% walked into a fire whilst fighting %killer%"
    FireTick:
      - "%player% burned to death"
    FireTickKill:
      - "%player% burnt into a crisp whilst fighting %killer%"
    Lava:
      - "%player% tried to swim in lava"
    LavaKill:
      - "%player% tried to swim in lava while trying to escape %killer%"
    Lightning: # Happens when struck by lightning, normally firetick/fireblock death message
      - "%player% went up in flames"
    Starvation:
      - "%player% starved to death"
    Suffocation:
      - "%player% suffocated in a wall"
    Void:
      - "%player% fell out of the world"
    VoidKill:
      - "%player% was knocked into the void by %killer%"
    FallShort: # Fall distance 5 blocks or less, or ender pearl
      - "%player% hit the ground too hard"
    FallLong: # Fall distance over 5 blocks
      - "%player% fell from a high place"
    FallKill:
      - "%player% was doomed to fall by %killer%"
    Elytra: 
      - "%player% experienced kinetic energy"
    Suicide: # Some plugins may use this one, used in /suicide and /kill for example
      - "%player% died"
    Melting: # Some plugins may use this one, originally for Snowmans + hot biomes
      - "%player% died"
    Custom: # Some plugins may use this one
      - "%player% died"
  unknown: 
    - "%player% died"
mob-names:
  Blaze: "Blaze"
  CaveSpider: "Cave Spider"
  Creeper: "Creeper"
  ElderGuardian: "Elder Guardian"
  EnderDragon: "Ender Dragon"
  Enderman: "Enderman"
  Endermite: "Endermite"
  Ghast: "Ghast"
  Giant: "Giant"
  Guardian: "Guardian"
  IronGolem: "Iron Golem"
  MagmaCube: "Magma Cube"
  Rabbit: "The Killer Bunny"
  Shulker: "Shulker"
  Silverfish: "Silverfish"
  Skeleton: "Skeleton"
  Slime: "Slime"
  SnowGolem: "Snow Golem"
  Spider: "Spider"
  Witch: "Witch"
  Wither: "Wither"
  WitherSkeleton: "Wither Skeleton"
  Wolf: "Wolf"
  Zombie: "Zombie"
  ZombiePigMan: "Zombie Pigman"

custom-mob-death-messages:
  # The following attribute takes in regular expressions and checks top-down whether the names of the mobs match them.
  # If there is no list, as in [], the plugin will look up the message from the normal death messages.
  # If the list only has an empty message, the death message for that mob will be hidden.
  # To match color codes, use the § character instead of &. (This file must be encoded in UTF-8)
  # Examples:
  #
  # "_*": # match all mobs
  #   - "%player% was killed by a mob"
  #
  # "^[Ss]_*": # match all mobs beginning with S or s
  #   - "%player% was killed by a mob"
  #
  # "§cMy Custom Boss": [] # display normal messages for mobs being 'My Custom Boss' written in red
  #
  # "My Custom Boss": # match all mobs with name being 'My Custom Boss'
  #   - "%player% was killed by a boss"
  #   - "%player% was pummeled by a boss"
  #
  # "§aMy Custom Boss": # match all mobs with name being 'My Custom Boss' written in light green
  #   - "%player% was killed by a boss"
  #   - "%player% was pummeled by a boss"
  #
  # "_*My Custom Boss_*": # match all mobs with name containing 'My Custom Boss'
  #   - "%player% was killed by a boss"
  #   - "%player% was pummeled by a boss"
  #
  # !!!!!!!!!!!!!!!!!!!!!!!! IMPORTANT !!!!!!!!!!!!!!!!!!!!!!!!
  #  IN REGEXES; ALL DOTS MUST BE REPRESENTED WITH UNDERSCORES
  # !!!!!!!!!!!!!!!!!!!!!!!! IMPORTANT !!!!!!!!!!!!!!!!!!!!!!!!
  #
  Melee:
    "_*": []
  Ranged:
    "_*": []
  Potion:
    "_*": []
  Thorns:
    "_*": []
  TNTKill:
    "_*": []
  CactusKill:
    "_*": []
  DrowningKill:
    "_*": []
  FireBlockKill:
    "_*": []
  FireTickKill:
    "_*": []
  LavaKill:
    "_*": []
  VoidKill:
    "_*": []
  FallKill:
    "_*": []
  Other:
    "_*": []

custom-user-death-messages:
  # Same deal here. The plugin checks from the actual user names of players.
  # custom-user-death-messages is preferred over custom-player-death-messages:
  # empty list here will pass to custom-player-death-messages before passing through to
  # normal death messages.
  Melee:
    "_*": []
  Ranged:
    "_*": []
  Potion:
    "_*": []
  Thorns:
    "_*": []
  TNTKill:
    "_*": []
  CactusKill:
    "_*": []
  DrowningKill:
    "_*": []
  FireBlockKill:
    "_*": []
  FireTickKill:
    "_*": []
  LavaKill:
    "_*": []
  VoidKill:
    "_*": []
  FallKill:
    "_*": []
  Other:
    "_*": []

custom-player-death-messages:
  # Same deal here. The plugin checks from the display names of players.
  Melee:
    "_*": []
  Ranged:
    "_*": []
  Potion:
    "_*": []
  Thorns:
    "_*": []
  TNTKill:
    "_*": []
  CactusKill:
    "_*": []
  DrowningKill:
    "_*": []
  FireBlockKill:
    "_*": []
  FireTickKill:
    "_*": []
  LavaKill:
    "_*": []
  VoidKill:
    "_*": []
  FallKill:
    "_*": []
  Other:
    "_*": []
