name: DeathMessagesPrime
main: net.memmove.bukkit.deathmsg.Main
version: 1.3
description: Very customizable death message interface.
author: CosmoConsole
commands:
   dmsg:
      description: Se vilken version som körs samt ladda om konfigurering.
      usage: /<kommando> [reload]
permissions:
   deathmessagesprime.*:
      description: Ger tillgång till Deathmessages alla funktioner.
      default: op
      children:
         deathmessagesprime.reload: true
         deathmessagesprime.debug: true
   deathmessagesprime.reload:
      description: Ger tillgång till Deathmessages konfigurering.
      default: op
   deathmessagesprime.debug:
      description: Skickar ut debugg meddelanden om debugg är aktivt.
      default: op
