name: DeathMessagesPrime
main: net.memmove.bukkit.deathmsg.Main
version: 1.3
description: Very customizable death message interface.
author: CosmoConsole
commands:
   dmsg:
      description: See the version of the plugin and reload it.
      usage: /<command> [reload]
permissions:
   deathmessagesprime.*:
      description: Gives access to all DeathMessagesPrime features.
      default: op
      children:
         deathmessagesprime.reload: true
         deathmessagesprime.debug: true
   deathmessagesprime.reload:
      description: Gives access to reload the DeathMessagesPrime plugin's configuration.
      default: op
   deathmessagesprime.debug:
      description: Broadcasts death debug information if debug mode is enabled.
      default: op