# PlaceholderInjector v1.6.3
# Created by extended_clip and GGhost
# 
# Allow placeholders in any chat window message from any plugin
# If you want to use placeholders in your essentials chat formatting
# you must use {<placeholder>} instead of %<placeholder>%
# If you would like messages created by the Spigot chat API intercepted also,
# (json messages with hover text, click events, etc)
# set intercept_spigot_chat_api_messages to true
# Set to false if you are not using Spigot!
# chat:
#   enabled: true/false
#   intercept_spigot_chat_api_messages: true/false
# 
# Allow placeholders in any ItemStack name, lore, or inventory title
# inventory: 
#   enabled: true/false
# 
# Allow placeholders in any title or subtitle from any plugin
# title:
#   enabled: true/false
# 
# Allow placeholders in the tab list header and footer
# tab:
#   enabled: true/false
# 
# Allow placeholders in signs:
# signs:
#   enabled: true/false
#   update_interval: <time in seconds to update sign placeholders, 0 to disable>
# 
# Allow placeholders in HolographicDisplays holograms
# holographicdisplays:
#   enabled: true/false
#   update_interval: <time in seconds to update holo placeholders>
# 
# 
# To add placeholders in chat messages, you need the permission node:
# placeholderinjector.chat.bypass
# 
# To add placeholders in sign lines, you need the permission node:
# placeholderinjector.signs.bypass

chat:
  enabled: true
  intercept_spigot_chat_api_messages: true
inventory:
  enabled: true
title:
  enabled: true
tab:
  enabled: true
signs:
  enabled: true
  update_interval: 30
holographicdisplays:
  enabled: true
  update_interval: 30
