# Configuration for EasyCarts
# Version: 1.5
# Author: Xericore
# 
# When players stop at an intersection, show an info message to the player.
ShowIntersectionMessage: true
IntersectionMessageText: Kolla åt det håll du vill fortsätta åka åt och tryck frammåt.
RemoveMinecartOnExit: false
MaxSpeedPercent: 400.0
MaxPushSpeedPercent: 100.0
PoweredRailBoostPercent: 200.0
SlowWhenEmpty: true
MinecartCollisions: false
