
# ########################################################################
# Rewards for killing mobs.
# ########################################################################
# Here is where you set the base prize in $ for killing a mob of each type
# You can either set a decimal number ex 1.23 or a range 1.23:2.23
# For each kill you can run a console command to give the player a reward.
# You can use the following variables:
# {killer},{killed},{player},{killed_player},{prize},{world},
# {killerpos},{killedpos}. Killerpos and Killedpos will have the 
# format <x> <y> <z>. Which could be used to /summon items. 
# An example could be /summon apple {killedpos} 2. to summon two apples where
# where the mob was killed or /summon apple {killerpos} 1. to summon an
# an apple where the player is.
# Another example could be to give the player permission to fly
# for 1 hour or use give command to the player items.
# You can also specify the message send to the player.
# You can run many console commands on each line, each command
# must be separated by |
# The player will have the cmd run in {mob-cmd-run-frequency} out of
# {mob-cmd-run-frequency-base} times in average. If mob-cmd-run-frequency=0 it
# will never run. If f.ex. mob-cmd-run-frequency=50 and 
# mob-cmd-run-frequency-base=100 it will run run every second time.
mobs:
  blaze: '1.0'
  blaze-cmd: ''
  blaze-cmd-desc: ''
  blaze-cmd-run-frequency: 10
  blaze-cmd-run-frequency-base: 100
  creeper: '1.0'
  creeper-cmd: ''
  creeper-cmd-desc: ''
  creeper-cmd-run-frequency: 5
  creeper-cmd-run-frequency-base: 100
  silverfish: '1.0'
  silverfish-cmd: ''
  silver-cmd-desc: ''
  silverfish-cmd-run-frequency: 10
  silverfish-cmd-run-frequency-base: 100
  zombie-pigman: '1.0'
  zombie-pigman-cmd: ''
  zombie-pigman-cmd-desc: ''
  zombie-pigman-cmd-run-frequency: 10
  zombie-pigman-cmd-run-frequency-base: 100
  enderman: '1.0'
  enderman-cmd: ''
  enderman-cmd-desc: ''
  enderman-cmd-run-frequency: 20
  enderman-cmd-run-frequency-base: 100
  giant: '1.0'
  giant-cmd: ''
  giant-cmd-desc: ''
  giant-cmd-run-frequency: 5
  giant-cmd-run-frequency-base: 100
  skeleton: '1.0'
  skeleton-cmd: ''
  skeleton-cmd-desc: ''
  skeleton-cmd-run-frequency: 5
  skeleton-cmd-run-frequency-base: 100
  wither-skeleton: '1.0'
  wither-skeleton-cmd: ''
  wither-skeleton-cmd-desc: ''
  wither-skeleton-cmd-run-frequency: 10
  wither-skeleton-cmd-run-frequency-base: 100
  spider: '1.0'
  spider-cmd: ''
  spider-cmd-desc: ''
  spider-cmd-run-frequency: 5
  spider-cmd-run-frequency-base: 100
  cave-spider: '1.0'
  cave-spider-cmd: ''
  cave-spider-cmd-desc: ''
  cave-spider-cmd-run-frequency: 10
  cave-spider-cmd-run-frequency-base: 100
  witch: '1.0'
  witch-cmd: ''
  witch-cmd-desc: ''
  witch-cmd-run-frequency: 5
  witch-cmd-run-frequency-base: 100
  zombie: '1.0'
  zombie-cmd: ''
  zombie-cmd-desc: ''
  zombie-cmd-run-frequency: 50
  zombie-cmd-run-frequency-base: 1000
  ghast: '1.0'
  ghast-cmd: ''
  ghast-cmd-desc: ''
  ghast-cmd-run-frequency: 10
  ghast-cmd-run-frequency-base: 100
  iron-golem: '1.0'
  iron-golem-cmd: ''
  iron-golem-cmd-desc: ''
  iron-golem-cmd-run-frequency: 10
  iron-golem-cmd-run-frequency-base: 100
  magma-cube: '1.0'
  magma-cube-cmd: ''
  magma-cube-cmd-desc: ''
  magma-cube-cmd-run-frequency: 10
  magma-cube-cmd-run-frequency-base: 100
  endermite: '1.0'
  endermite-cmd: ''
  endermite-cmd-desc: ''
  endermite-cmd-run-frequency: 10
  endermite-cmd-run-frequency-base: 100
  guardian: '1.0'
  guardian-cmd: ''
  guardian-cmd-desc: ''
  guardian-cmd-run-frequency: 10
  guardian-cmd-run-frequency-base: 100
  killerrabbit: '1.0'
  killerrabbit-cmd: ''
  killerrabbit-cmd-desc: ''
  killerrabbit-cmd-run-frequency: 25
  killerrabbit-cmd-run-frequency-base: 100

  # This is multiplied by the size of the slime. So a big natural slime is 4x this value
  slime-base: '1.0'
  slime-cmd: ''
  slime-cmd-desc: ''
  slime-cmd-run-frequency: 5
  slime-cmd-run-frequency-base: 100
  shulker: '1.0'
  shulker-cmd: ''
  shulker-cmd-desc: ''
  shulker-cmd-run-frequency: 50

# ########################################################################
# Rewards for killing bosses
# ########################################################################
# Here is where you set the base prize in $ for killing the bosses
boss:
  wither: '1.0'
  wither-cmd: ''
  wither-cmd-desc: ''
  wither-cmd-run-frequency: 100
  wither-cmd-run-frequency-base: 100
  enderdragon: '1.0'
  enderdragon-cmd: ''
  enderdragon-cmd-desc: ''
  enderdragon-cmd-run-frequency: 100
  enderdragon-cmd-run-frequency-base: 100

# ########################################################################
# Rewards for killing passive mobs
# ########################################################################
# Here is where you set the base prize in $ for killing passive/friendly mobs.
# By default the player does not get a reward for killing friendly mobs.
# If you make the number negative, the reward will be a fine for killing a passive animal.
passive:
  bat: '0'
  bat-cmd: ''
  bat-cmd-desc: ''
  bat-cmd-run-frequency: 0
  bat-cmd-run-frequency-base: 100
  chicken: '0'
  chicken-cmd: ''
  chicken-cmd-desc: ''
  chicken-cmd-run-frequency: 0
  chicken-cmd-run-frequency-base: 100
  cow: '5'
  cow-cmd: ''
  cow-cmd-desc: ''
  cow-cmd-run-frequency: 0
  cow-cmd-run-frequency-base: 100
  horse: '0'
  horse-cmd: ''
  horse-cmd-desc: ''
  horse-cmd-run-frequency: 0
  horse-cmd-run-frequency-base: 100
  mushroom-cow: '0'
  mushroom-cow-cmd: ''
  mushroom-cow-cmd-desc: ''
  mushroom-cow-cmd-run-frequency: 0
  mushroom-cow-cmd-run-frequency-base: 100
  ocelot: '0'
  ocelot-cmd: ''
  ocelot-cmd-desc: ''
  ocelot-cmd-run-frequency: 0
  ocelot-cmd-run-frequency-base: 100
  pig: '0'
  pig-cmd: ''
  pig-cmd-desc: ''
  pig-cmd-run-frequency: 0
  pig-cmd-run-frequency-base: 100
  rabbit: '0'
  rabbit-cmd: ''
  rabbit-cmd-desc: ''
  rabbit-cmd-run-frequency: 0
  rabbit-cmd-run-frequency-base: 100
  sheep: '0'
  sheep-cmd: ''
  sheep-cmd-desc: ''
  sheep-cmd-run-frequency: 0
  sheep-cmd-run-frequency-base: 100
  snowman: '0'
  snowman-cmd: ''
  snowman-cmd-desc: ''
  snowman-cmd-run-frequency: 0
  snowman-cmd-run-frequency-base: 100
  squid: '0'
  squid-cmd: ''
  squid-cmd-desc: ''
  squid-cmd-run-frequency: 0
  villager: '-100'
  villager-cmd: ''
  villager-cmd-desc: ''
  villager-cmd-run-frequency: 0
  villager-cmd-run-frequency-base: 100
  wolf: '-10'
  wolf-cmd: ''
  wolf-cmd-desc: ''
  wolf-cmd-run-frequency: 0
  wolf-cmd-run-frequency-base: 100

# ########################################################################
#  Bonus multipliers
# ########################################################################
# These are bonus multipliers that can modify the base prize. 
# REMEMBER: These are not in $ but they are a multiplier. 
# Setting to 1 will disable them.
bonus:
  sneaky: 2.0
  return-to-sender: 2.0
  push-off-cliff: 2.0
  no-weapon: 2.0
  far-shot: 4.0
  mounted: 1.5
  friendly-fire: 4.0
  bonus-mob: 10.0
  critical: 2.0

  # This is the chance (% chance 0-100) that a bonus mob will spawn.
  bonus-mob-chance: 0.2

  # Bonus for killing a Baby mob.
  babyMultiplier: 1.2

# ########################################################################
# Special / Achievements rewards
# ########################################################################
# Here is where you set the prize in $ for achieving a special kill. 
# For each achievment you can run a console command to give the player a reward. 
# You can use the following variables {player},{world}.
# An example could be to give the player permission to fly 
# for 1 hour or use give command to the player items.
# You can also specify the message send to the player.
# You can run many console commands on each line, each command
# must be separated by |
special:
  charged-kill: 1.0
  charged-kill-cmd: ''
  charged-kill-cmd-desc: ''
  creeper-punch: 1.0
  creeper-punch-cmd: ''
  creeper-punch-cmd-desc: ''
  axe-murderer: 1.0
  axe-murderer-cmd: ''
  axe-murderer-cmd-desc: ''
  recordhungry: 1.0
  recordhungry-cmd: ''
  recordhungry-cmd-desc: ''
  infighting: 1.0
  infighting-cmd: ''
  infighting-cmd-desc: ''
  by-the-book: 1.0
  by-the-book-cmd: ''
  by-the-book-cmd-desc: ''
  creepercide: 1.0
  creepercide-cmd: ''
  creepercide-cmd-desc: ''
  hunt-begins: 1.0
  hunt-begins-cmd: ''
  hunt-begins-cmd-desc: ''
  itsmagic: 1.0
  itsmagic-cmd: ''
  itsmagic-cmd-desc: ''
  fancypants: 1.0
  fancypants-cmd: ''
  fancypants-cmd-desc: ''
  master-sniper: 1.0
  master-sniper-cmd: ''
  master-sniper-cmd-desc: ''
  fangmaster: 1.0
  fangmaster-cmd: ''
  fangmaster-cmd-desc: ''
  hunter1: 1.0
  hunter1-cmd: ''
  hunter1-cmd-desc: ''
  hunter2: 1.0
  hunter2-cmd: ''
  hunter2-cmd-desc: ''
  hunter3: 1.0
  hunter3-cmd: ''
  hunter3-cmd-desc: ''
  hunter4: 1.0
  hunter4-cmd: ''
  hunter4-cmd-desc: ''
  hunter5: 1.0
  hunter5-cmd: ''
  hunter5-cmd-desc: ''
  hunter6: 1.0
  hunter6-cmd: ''
  hunter6-cmd-desc: ''
  hunter7: 1.0
  hunter7-cmd: ''
  hunter7-cmd-desc: ''

# ########################################################################
# Rewards for assisting killings
# ########################################################################
# They players can get an extra reward if they help each other killing mobs.
assists:

  # Enabling assist allows the second last player to attack a mob to get some money from it
  enable: true

  # This should be a value that is multiplied against the mobs base kill value.
  # This is used to determine how much money an assister gets.
  multiplier: 0.25

  # Should killstreak be applied to assists
  allow-killstreak: false

  # Time in seconds after attacking a mob that can be counted as an assist
  timeout: 4

# ########################################################################
# Penalty multipliers
# ########################################################################
# These are penalty multipliers that can modify the base prize. 
# REMEMBER: These are not in $ but they are a multiplier. 
# Setting to 1 will disable them.
penalty:

  # Enabling this prevents a player from earning too much money from using a mob grinder
  enable-grinding-penalty: true

  # If a player flies at any point in a fight, this penalty will be applied
  flyingPenalty: 0.5

# ########################################################################
# Reward for kills in a row
# ########################################################################
# Set the multiplier when the player kills 1,2,3,4 mob in a row without getting damage.
killstreak:
  level1: 5
  level1-multiplier: 1.5
  level2: 10
  level2-multiplier: 2.0
  level3: 20
  level3-multiplier: 3.0
  level4: 40
  level4-multiplier: 4.0

# ########################################################################
# Rank multipliers
# ########################################################################
# You can add multipliers for players with different ranks/groups. To do this
# you must set give the user/group permissions with a format like this:
# mobhunting.multiplier.guest
# mobhunting.multiplier.guardian
# mobhunting.multiplier.staff
# mobhunting.multiplier.hasVoted
# mobhunting.multiplier.donator
# mobhunting.multiplier.op <---- Notice 'op' is reserved for OP'ed players!
# OP'ed players will only get the OP multiplier
# you can make your own permission nodes. You just need to keep the format
# mobhunting.multiplier.name 'value' in your permissions file and the format below in this file.
multiplier:
  rank-multiplier:
    mobhunting:
      multiplier:
        staff: '1.05'
        guardian: '1.02'
        donator: '3'
        guest: '0.9'
        hasVoted: '2'

# ########################################################################
# Pvp rewards
# ########################################################################
# Pvp configuration. Set pvp-allowed = true if you want give the players a reward when they kill eachother.
# You can alsp run a console command when this happens to give the player a reward or punish him.
# You can you the following variables {player},{world},{killed_player}.
# An example could be to give the player permission to fly 
# for 1 hour or use give command to the player items.
# You can also specify the message send to the player.
# You can run many console commands on each line, each command
# must be separated by |
pvp:

  # Set pvpAllowed=false to disable rewards on killing other players.
  pvp-allowed: true

  # Set rob-from-victim=true to steal from the victim or 
  # rob-from-victim=false to get the reward mpney from the server.
  rob-from-victim: true

  # The kill prize kan be a number to stel x dollars from the killed player,
  # or it kan be a cut in percent of his balance.
  pvp-kill-prize: 1.5%

  # One or more console commands to be run when a player kills another player.
  pvp-kill-cmd: ''

  # Write the message to the killer, describing the reward / console commands
  pvp-kill-cmd-desc: ''

# ########################################################################
# Disguises rewards
# ########################################################################
# Here is where can define the actions when a player is under disguise (attacker)
#  or when the attacked (victim)
disguises:

  # Disable integration with iDisguise
  disable-integration-i-disguise: true

  # Disable integration with DisguiseCcraft
  disable-integration-disguisecraft: true

  # Disable integration with LibsDisguises
  disable-integration-libsdisguises: true

  # Set pvpAllowed=false to disable rewards on killing other players.
  remove-disguise-when-attacking: true

  # Set pvpAllowed=false to disable rewards on killing other players.
  remove-disguise-when-attacked: true

  # Bonus multiplier for killing while disgused.
  # Can be both positive an negative = reward or penalty
  # and over and under 1 = raise or lower the reward. 
  undercover-multiplier: 0.95

  # Bonus multiplier for killing a disgused player.
  # Can be both positive an negative = reward or penalty
  # and over and under 1 = raise or lower the reward. 
  cover-blown-multiplier: 1.2

# ########################################################################
# Integration to otherplugins.
# ########################################################################
plugins:

  # Disable integration with MobArena
  disable-integration-mobarena: true

  # Set to true if you want the players to get rewards while playing MobArena.
  mobarena-get-rewards: false

  # Disable integration with PvpArena
  disable-integration-pvparena: true

  # Set to true if you want the players to get rewards while playing pvpArena.
  pvparena-get-rewards: false

  # Disable integration with Citizens2
  disable-integration-citizens: false

  # Disable integration with MythicMobs
  disable-integration-mythicmobs: false

  # Disable integration with MyPet
  disable-integration-mypet: true

  # Disable integration with MiniGames
  disable-integration-minigames: true

  # Disable integration with WorldGuard
  disable-integration-worldguard: false

  # Disable integration with Essentials
  disable-integration-essentials: false

# ########################################################################
# Database Settings.
# ########################################################################
database:

  # Type of database to use. Valid values are: sqlite, mysql
  type: sqlite
  username: user
  password: password
  host: localhost:3306
  database: mobhunting

# ########################################################################
# Update settings
# ########################################################################
updates:

  # Check if there is a new version of the plugin available.
  update-check: true

  # Set the number of seconds between each check. Recommended setting is
  # check_every: 3600 ~ to check every hour.
  check_every: 3600

  # Set 'autoupdate: true' if you want new updates downloaded and installed.
  # You will still have to reboot the server manually.
  autoupdate: false

# ########################################################################
# NPC / Citizens / MasterMobHunter settings.
# ########################################################################
npc:

  # Set the number of seconds between each check. Recommended setting is
  # masterMobHunter_check_every: 300 ~ to update all MasterMobHunters every 5th minute.
  masterMobHunter_check_every: 300

# ########################################################################
# General Setting.
# ########################################################################
general:

  # Put the names of the worlds here that you do not wish for mobhunting to be enabled in.
  disabled-in-worlds: []

  # The language (file) to use. You can put the name of the language file as the language code 
  # (eg. en_US, de_DE, fr_FR, ect.) or you can specify the name of a custom file without the .lang
  # Please check the lang/ folder for a list of all available translations.
  language: en_US

  # Can the players earn money on mobs spawned from mobspawners and eggs?
  allow_mobspawners_and_eggs: false

  # Should achievements be broadcasted?
  broadcast-achievement: true

  # Should the hunt begins achievement be broadcasted?
  broadcast-first-achievement: true

  # Time between saves in ticks (20 ticks ~ 1 sec)
  save-period: 6000

  # Time between leaderboard updates in ticks (20 ticks ~ 1 sec)
  leaderboard-update-period: 1200

  # Time in seconds after attacking a mob that can be counted as a kill
  kill-timeout: 4

  # If kills are not being registered in mob hunting. Enable this to see why they arent
  kill-debug: false

  # Rounding of rewards when you uses a range or %. (ex creeperPrize=10:30) the reward.
  # All numbers except 0 can be used. 
  # Set rounding_reward=1 if you want integers. IE. 10,11,12,13,14...
  # Set rounding_reward=0.01 if you want 2 decimals 10.00, 10.01, 10.02... integers.
  # Set rounding_reward=5 if you want multipla of 5 IE. 10,15,20,25...
  # Set rounding_reward=2 if you want multipla of 2 IE. 10,12,14,16...
  reward_rounding: 0.01

  # When a new playerjoins the server he will by default start
  # in 'LEARNING MODE' and get extra information about when he get rewards and not,
  # when killing Mobs. The player can disable this InGame by using the command '/mh learn'
  newplayer_learning_mode: true
