MyPet:
  Leash:
    Consume: true
    ShowAlwaysForOwner: false
  OwnerCanAttackPet: false
  DisablePetVersusPlayer: false
  RemovePetsAfterRelease: false
  FollowStartDistance: 7.0
  ReleasePetsOnDeath: false
  RetainEquipmentOnTame: true
  Make-Pet-Invisible-When-Owner-Is-Invisible: true
  Log:
    Level: INFO
    INFO: true
    ERROR: true
    WARNING: true
  Update-Check: true
  Repository:
    NBT:
      AutoSaveTime: 60
      Pet:
        SaveOnAdd: true
        SaveOnUpdate: true
        SaveOnRemove: true
      Player:
        SaveOnAdd: true
        SaveOnUpdate: true
        SaveOnRemove: true
      Backup:
        Active: true
        SaveInterval: 1440
        DateFormat: yyyy_MM_dd_HH.mm
  Respawn:
    Time:
      Default:
        Factor: 5
        Fixed: 0
      Player:
        Factor: 5
        Fixed: 0
    EconomyCost:
      Fixed: 0.0
      Factor: 1.0
  Permissions:
    Enabled: true
    UseExtendedPermissions: false
  LevelSystem:
    CalculationMode: Default
    Firework:
      Enabled: true
      Color: '#00FF00'
  HungerSystem:
    Active: true
    Time: 60
    HungerPointsPerFeed: 6
  Skilltree:
    AutomaticAssignment: false
    RandomAssignment: false
    InheritAlreadyInheritedSkills: false
    ChooseOnce: true
    PreventLevellingWithout: true
    SwitchPenaltyFixed: 0.0
    SwitchPenaltyPercent: 5
    SwitchPenaltyAdmin: false
  Hooks:
    BungeeCord:
      UUID-Mode: online
    Towny: true
    Heroes: true
    Factions: true
    WorldGuard: true
    Citizens: true
    mcMMO: true
    Regios: true
    MobArena:
      PvP: true
      DisablePetsInArena: false
    Residence: true
    AncientRPG: true
    GriefPrevention: true
    PvPManager: true
    Minigames:
      DisablePetsInGames: true
    PvPArena:
      DisablePetsInArena: true
      PvP: true
    SurvivalGames:
      PvP: true
      DisablePetsInGames: true
    MyHungerGames:
      DisablePetsInGames: true
    BattleArena:
      DisablePetsInArena: true
    Vault:
      Economy: true
    SkillAPI:
      GrantExp: true
      Disable-Vanilla-Exp: false
  Name:
    Filter:
    - whore
    - fuck
    MaxLength: 32
    OverHead:
      Visible: true
      Prefix: <aqua>
      Suffix: ''
  Exp:
    DamageWeightedExperienceDistribution: false
    Passive:
      Always-Grant-Passive-XP: true
      PercentPerMonster: 25
    Loss:
      Percent: 0
      Fixed: 0.0
      Drop: true
    Gain:
      MonsterSpawner: true
    LevelCap: 100
    Active:
      CREEPER:
        Min: 5.0
        Max: 5.0
      SKELETON:
        Min: 5.0
        Max: 5.0
      SPIDER:
        Min: 5.0
        Max: 5.0
      GIANT:
        Min: 25.0
        Max: 25.0
      ZOMBIE:
        Min: 5.0
        Max: 5.0
      SLIME:
        Min: 1.0
        Max: 4.0
      GHAST:
        Min: 5.0
        Max: 5.0
      PIG_ZOMBIE:
        Min: 5.0
        Max: 5.0
      ENDERMAN:
        Min: 5.0
        Max: 5.0
      CAVE_SPIDER:
        Min: 5.0
        Max: 5.0
      SILVERFISH:
        Min: 5.0
        Max: 5.0
      BLAZE:
        Min: 10.0
        Max: 10.0
      MAGMA_CUBE:
        Min: 1.0
        Max: 4.0
      ENDER_DRAGON:
        Min: 20000.0
        Max: 20000.0
      WITHER:
        Min: 100.0
        Max: 100.0
      BAT:
        Min: 1.0
        Max: 1.0
      WITCH:
        Min: 10.0
        Max: 10.0
      ENDERMITE:
        Min: 3.0
        Max: 3.0
      GUARDIAN:
        Min: 10.0
        Max: 10.0
      PIG:
        Min: 1.0
        Max: 3.0
      SHEEP:
        Min: 1.0
        Max: 3.0
      COW:
        Min: 1.0
        Max: 3.0
      CHICKEN:
        Min: 1.0
        Max: 3.0
      SQUID:
        Min: 1.0
        Max: 3.0
      WOLF:
        Min: 1.0
        Max: 3.0
      MUSHROOM_COW:
        Min: 1.0
        Max: 3.0
      SNOWMAN:
        Min: 0.0
        Max: 0.0
      OCELOT:
        Min: 1.0
        Max: 3.0
      IRON_GOLEM:
        Min: 0.0
        Max: 0.0
      RABBIT:
        Min: 1.0
        Max: 1.0
      VILLAGER:
        Min: 0.0
        Max: 0.0
      ENDER_CRYSTAL:
        Min: 10.0
        Max: 10.0
      EnderCrystal:
        Min: 10.0
        Max: 10.0
      Spider:
        Min: 5.0
        Max: 5.0
      Endermite:
        Min: 3.0
        Max: 3.0
      Ghast:
        Min: 5.0
        Max: 5.0
      Silverfish:
        Min: 5.0
        Max: 5.0
      Cow:
        Min: 1.0
        Max: 3.0
      Rabbit:
        Min: 1.0
        Max: 1.0
      Enderman:
        Min: 5.0
        Max: 5.0
      VillagerGolem:
        Min: 0.0
        Max: 0.0
      Wolf:
        Min: 1.0
        Max: 3.0
      Skeleton:
        Min: 5.0
        Max: 5.0
      Bat:
        Min: 1.0
        Max: 1.0
      Creeper:
        Min: 5.0
        Max: 5.0
      LavaSlime:
        Min: 1.0
        Max: 4.0
      Blaze:
        Min: 10.0
        Max: 10.0
      WitherBoss:
        Min: 100.0
        Max: 100.0
      Squid:
        Min: 1.0
        Max: 3.0
      EnderDragon:
        Min: 20000.0
        Max: 20000.0
      Villager:
        Min: 0.0
        Max: 0.0
      Witch:
        Min: 10.0
        Max: 10.0
      MushroomCow:
        Min: 1.0
        Max: 3.0
      Guardian:
        Min: 10.0
        Max: 10.0
      Chicken:
        Min: 1.0
        Max: 3.0
      Sheep:
        Min: 1.0
        Max: 3.0
      Ozelot:
        Min: 1.0
        Max: 3.0
      PigZombie:
        Min: 5.0
        Max: 5.0
      Slime:
        Min: 1.0
        Max: 4.0
      CaveSpider:
        Min: 5.0
        Max: 5.0
      Pig:
        Min: 1.0
        Max: 3.0
      SnowMan:
        Min: 0.0
        Max: 0.0
      Zombie:
        Min: 5.0
        Max: 5.0
      Giant:
        Min: 25.0
        Max: 25.0
  Skill:
    Control:
      Item: 420
    Ride:
      Item: 420
      HungerPerMeter: 0.01
    Inventory:
      Creative: true
      DropWhenOwnerDies: true
    Beacon:
      HungerDecreaseTime: 100
      Party-Support: true
    Behavior:
      Aggro: true
      Farm: true
      Friendly: true
      Raid: true
      Duel: true
  Info:
    Wiki-URL: http://mypet.keyle.de
    AdminOnly:
      PetName: false
      PetOwner: false
      PetHP: false
      PetDamage: false
      PetHunger: true
      PetLevel: true
      PetEXP: true
      PetSkilltree: true
    OverHead:
      Name: true
      Prefix: <aqua>
      Suffix: ''
  ZombieVsMyPet: true
  MaxPetNameLength: 64
  Backup:
    Active: true
    SaveInterval: 1440
    DateFormat: yyyy_MM_dd_HH.mm
  PetStorage:
    AutoSaveTime: 60
    OnPlayerQuit: true
    OnPetLeash: true
    OnPetRelease: true
  Pets:
    Chicken:
      CanLayEggs: true
      GrowUpItem: 373
      HP: 20.0
      Speed: 0.3
      Food: '295'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Cow:
      CanGiveMilk: true
      GrowUpItem: 373
      HP: 20.0
      Speed: 0.3
      Food: '296'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Sheep:
      CanBeSheared: true
      CanRegrowWool: true
      GrowUpItem: 373
      HP: 20.0
      Speed: 0.3
      Food: '296'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    IronGolem:
      CanThrowUp: true
      HP: 20.0
      Speed: 0.3
      Food: '265'
      LeashFlags: UserCreated
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Snowman:
      FixSnowTrack: true
      HP: 20.0
      Speed: 0.3
      Food: 141;332
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Horse:
      GrowUpItem: 297
      HP: 20.0
      Speed: 0.3
      Food: 353;296;260
      LeashFlags: Tamed
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Mooshroom:
      GrowUpItem: 373
      CanGiveStew: false
      HP: 20.0
      Speed: 0.3
      Food: '296'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Ocelot:
      GrowUpItem: 373
      HP: 20.0
      Speed: 0.3
      Food: '349'
      LeashFlags: Tamed
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Pig:
      GrowUpItem: 373
      HP: 20.0
      Speed: 0.3
      Food: '391'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Villager:
      GrowUpItem: 373
      HP: 20.0
      Speed: 0.3
      Food: '260'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Wolf:
      GrowUpItem: 373
      HP: 20.0
      Speed: 0.3
      Food: 363;365
      LeashFlags: Tamed
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Zombie:
      GrowUpItem: 373
      HP: 20.0
      Speed: 0.3
      Food: '367'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    PigZombie:
      GrowUpItem: 373
      HP: 20.0
      Speed: 0.3
      Food: '367'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Rabbit:
      GrowUpItem: 373
      HP: 20.0
      Speed: 0.3
      Food: 141;38
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Bat:
      HP: 20.0
      Speed: 0.3
      Food: '375'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Blaze:
      HP: 20.0
      Speed: 0.3
      Food: '289'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    CaveSpider:
      HP: 20.0
      Speed: 0.3
      Food: '367'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Creeper:
      HP: 20.0
      Speed: 0.3
      Food: '289'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Enderman:
      HP: 20.0
      Speed: 0.3
      Food: '88'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Endermite:
      HP: 20.0
      Speed: 0.3
      Food: '353'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Ghast:
      HP: 20.0
      Speed: 0.3
      Food: '289'
      LeashFlags: Impossible
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Giant:
      HP: 20.0
      Speed: 0.3
      Food: '367'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Guardian:
      HP: 20.0
      Speed: 0.3
      Food: '353'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    MagmaCube:
      HP: 20.0
      Speed: 0.3
      Food: '331'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Silverfish:
      HP: 20.0
      Speed: 0.3
      Food: '353'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Skeleton:
      HP: 20.0
      Speed: 0.3
      Food: '352'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Slime:
      HP: 20.0
      Speed: 0.3
      Food: '353'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Spider:
      HP: 20.0
      Speed: 0.3
      Food: '367'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Squid:
      HP: 20.0
      Speed: 0.3
      Food: '349'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Witch:
      HP: 20.0
      Speed: 0.3
      Food: '282'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
    Wither:
      HP: 20.0
      Speed: 0.3
      Food: '352'
      LeashFlags: Impossible
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
