# PlaceholderAPI version 2.3.7
# Created by extended_clip

check_updates: true
cloud_enabled: true
injector_enabled: true
boolean:
  'true': 'yes'
  'false': 'no'
date_format: YYYY/MM/dd HH:mm:ss
expansions:
  vault:
    formatting:
      thousands: k
      trillions: T
      quadrillions: Q
      billions: B
      millions: M
