name: AdvancedAchievements
main: com.hm.achievement.AdvancedAchievements
version: 2.4.2
author: DarkPyves
softdepend: [Vault]
load: POSTWORLD
description: Advanced Achievements erbjuder unika och utmanande Achievements. Försök samla så många du kan, intjäna belöningar, klättra på rankingen och mottag en RP bok!
website: https://github.com/PyvesB/AdvancedAchievements
commands:
  aach:
    description: Huvudkommandot för Advanced Achievements, använd för att se underkommandon. 
    aliases: [advancedachievements,aachievements,aa]  
    usage: /<command>
permissions:  
  achievement.book:
    description: Möjliggör mottagande av Achievements boken.
    default: true
  achievement.list:
    description: Möjliggör att se namnen på avklarade och saknade Achievements.
    default: true
  achievement.reload:
    description: Möjliggör att ladda om konfigurationen.
    default: op
  achievement.give:
    description: Möjliggör tilldelning av Achievements med kommando.
    default: op
  achievement.check:
    description: Möjliggör att se om Achievements mottagits av andra spelare.
    default: op
  achievement.delete:
    description: Möjliggör radering av Achievements med kommando.
    default: op
  achievement.update:
    description: Möjliggör underrättelse om uppdateringar till Advanced Achievements om CheckForUpdate är satt till true i konfig.
    default: op
  achievement.*:
    description: Rättigheten avslutad med stjärna inkluderar alla rättigheter nämnda ovan och inaktiverar fördröjning på bok och listnings kommando.
    default: op
    children:
      achievement.get: true
      achievement.book: true
      achievement.list: true
      achievement.reload: true
      achievement.give: true
      achievement.check: true
      achievement.delete: true
      achievement.update: true  
  achievement.count.connections:
    description: Möjliggör statistik i databasen över inloggningar att öka.
    default: true
  achievement.count.arrows:
    description: Möjliggör statistik i databasen över pilar avfyrade att öka.
    default: true
  achievement.count.beds:
    description: Möjliggör statistik i databasen över sängar använda att öka.
    default: true
  achievement.count.consumedpotions:
    description: Möjliggör statistik i databasen över förtärda bryggder att öka.
    default: true 
  achievement.count.eatenitems:
    description: Möjliggör statistik i databasen över saker ätna att öka.
    default: true
  achievement.count.deaths:
    description: Möjliggör statistik i databasen över dödsfall att öka.
    default: true
  achievement.count.itemdrops:
    description: Möjliggör statistik i databasen över saker slängda att öka.
    default: true
  achievement.count.enchantments:
    description: Möjliggör statistik i databasen över förtrollningar att öka.
    default: true
  achievement.count.fish:
    description: Möjliggör statistik i databasen över fiske att öka.
    default: true
  achievement.count.hoeplowings:
    description: Möjliggör statistik i databasen över lie att öka.
    default: true
  achievement.count.fertilising:
    description: Möjliggör statistik i databasen över gödsling att öka.
    default: true
  achievement.count.fireworks:
    description: Möjliggör statistik i databasen över fyverkerier att öka.
    default: true
  achievement.count.itembreaks:
    description: Möjliggör statistik i databasen över förstörda objekt att öka.
    default: true
  achievement.count.milk:
    description: Möjliggör statistik i databasen över mjölkning att öka.
    default: true
  achievement.count.shear:
    description: Möjliggör statistik i databasen över klippning att öka.
    default: true
  achievement.count.snowballs:
    description: Möjliggör statistik i databasen över snöbollar att öka.
    default: true
  achievement.count.eggs:
    description: Möjliggör statistik i databasen över ägg att öka.
    default: true
  achievement.count.taming:
    description: Möjliggör statistik i databasen över tämjning att öka.
    default: true
  achievement.count.trades:
    description: Möjliggör statistik i databasen över handel att öka.
    default: true
  achievement.count.anvilsused:
    description: Möjliggör statistik i databasen över användning av städ att öka.
    default: true
  achievement.count.brewing:
    description: Möjliggör statistik i databasen över bryggning att öka.
    default: true
  achievement.count.maxlevel:
    description: Möjliggör statistik i databasen över maxnivå att öka.
    default: true
  achievement.count.playedtime:
    description: Möjliggör statistik i databasen över speltid att öka.
    default: true
  achievement.count.distancefoot:
    description: Möjliggör statistik i databasen över avstånd till fots att öka.
    default: true
  achievement.count.distanceboat:
    description: Möjliggör statistik i databasen över avstånd med båt att öka.
    default: true
  achievement.count.distanceminecart:
    description: Möjliggör statistik i databasen över avstånd med vagn att öka.
    default: true
  achievement.count.distancehorse:
    description: Möjliggör statistik i databasen över avstånd på hästrygg att öka.
    default: true
  achievement.count.distancepig:
    description: Möjliggör statistik i databasen över avstånd med gris att öka.
    default: true
# Additional permissions are available for the breaks, places, crafts and kills categories.
# They depend on the sub-categories defined; for instance for stone breaks: achievement.count.breaks.stone