# +--------------------------------------+
#  TitleAction
#  config.yml
# +--------------------------------------+
# Hook:
#   WorldGuard: <true/false>
#   Factions: <true/false>
#   Towny: <true/false>
#   GriefPrevention: <true/false>
#   MineResetLite: <true/false>
#   Districts: <true/false>
#   Residence: <true/false>
#   PrisonReloaded: <true/false>
#   PlotSquared: <true/false>
#   PlotMe: <true/false>
#   TerrainControl: <true/false>
#   MultiverseCore: <true/false>
#   LandLord: <true/false>
#   PreciousStones: <true/false>
#   PrisonMines: <true/false>
#   Plotz: <true/false>
#   RegionForSale: <true/false>
#   PopulationDensity: <true/false>
#   AreaShop: <true/false>
#   ASkyblock: <true/false>
#   RedProtect: <true/false>
#   uSkyblock: <true/false>
# Biomes_Area: false
# Item_Default_Lang: <country_code More detail please see it on below>
#   Available languages > en_us, zh_tw, zh_cn, ko_kr,
#                         ja_jp, fr_fr, en_gb, de_de,
#                         pl_pl, es_es
# Delay_Title_When_Login:
#   Enable: <true/false>
#   Delay: <delay tick> # 20 tick = 1 sec
# Broadcast:
#   Enable: <true/false>
#   Interval: <tick>
#   FadeIn_Time: <tick>
#   Stay_Time: <tick>
#   FadeOut_Time: <tick>
#   Active_Sounds: <Sound~Delay~Volume~Pitch>[;<...>] or ""
#   Messages:
#   - Override_User_Option: <true/false>
#     Title: <Upper title> or ""
#     SubTitle: <Small title> or ""
#     ActionBar: <Message on action bar> or ""
# 
# +--------------------------------------+
# Remarks
# -------
# Hook - Hook in other plugins
# Delay_Title_When_Login - Delay player
#       title show when login
# Factions is included FactionsUUID and
#       the latest version
# +--------------------------------------+

Hook:
  WorldGuard: false
  Factions: false
  Towny: false
  GriefPrevention: true
  MineResetLite: false
  Districts: false
  Residence: false
  PrisonReloaded: false
  PlotSquared: false
  PlotMe: false
  TerrainControl: false
  MultiverseCore: false
  LandLord: false
  PreciousStones: false
  PrisonMines: false
  Plotz: false
  RegionForSale: false
  PopulationDensity: false
  AreaShop: true
  ASkyblock: false
  RedProtect: false
  uSkyBlock: false
Biomes_Area: false
Item_Default_Lang: en_us
Disable_Title_When_Spectator_Mode: false
Delay_Title_When_Login:
  Enable: false
  Delay: 60
Broadcast:
  Enable: false
  Interval: 600
  FadeIn_Time: 10
  Stay_Time: 60
  FadeOut_Time: 10
  Active_Sounds: ''
  Messages:
  - ActionBar: ''
    SubTitle: '&aTitleAction'
    Title: '&aDefault boardcast &fmessage!'
  - ActionBar: '&6~~~ TitleAction ~~~'
    SubTitle: ''
    Title: '&6Default second boardcast &fmessage!'
