# 
# set to 0 to disable economy
blankchance: 0.05
map-id: 1460
card-cost: 500
winning-action: levelupsound
losing-action: nothing
options:
  xmas-particles: false
messages:
  player-only: '&cLedsen, men det kommandot kan endast köras av en spelare!'
  not-a-number: '&cDu måste specifiera ett nummer, inte ett ord.'
  no-permissions: '&cDu saknar rättigheterna för det!'
  title-won: '&6Du har vunnit!'
  subtitle-won: '%item%'
  title-lost: '&cDu vann ingenting :('
  subtitle-lost: '&cBättre lycka nästa gång!'
  scratch-tutorial: '&aDucka (SHIFT) och rör muspekaren för att skrapa!'
  card-received: '&aDu har fått en skraplott!'
  card-bought: '&aDu har köpt en skraplott!'
  not-enough-money: '&cDu har inte tillräckligt med pengar för att köpa en skraplott!'
  already-scratching: '&cDu har redan en skraplott att skrapa! Klicka igen för att
    kasta den gamla och skrapa denna istället.'
carditem:
  ==: org.bukkit.inventory.ItemStack
  type: PAPER
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §eSkraplott
    lore:
    - §7Högerklicka för att aktivera skraplotten!
zombie:
  map-id: 1539
  items:
    '1452219521743':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1533
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/zombie.png[1/6]
      chance: 20
    '1452219525243':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1534
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/zombie.png[2/6]
      chance: 20
    '1452219532951':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1535
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/zombie.png[3/6]
      chance: 15
    '1452219535851':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1536
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/zombie.png[4/6]
      chance: 15
    '1452219540201':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1537
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/zombie.png[5/6]
      chance: 20
    '1452219546501':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1538
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/zombie.png[6/6]
      chance: 20
blaze:
  map-id: 1540
  items:
    '1452399477171':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1541
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/blaze.png[1/6]
      chance: 20
    '1452399484563':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1542
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/blaze.png[2/6]
      chance: 10
    '1452399490397':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1543
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/blaze.png[3/6]
      chance: 20
    '1452399493225':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1544
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/blaze.png[4/6]
      chance: 15
    '1452399495555':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1545
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/blaze.png[5/6]
      chance: 20
    '1452399500106':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1546
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/blaze.png[6/6]
      chance: 20
jockey:
  map-id: 1553
  items:
    '1452399685123':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1547
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/jockey.png[1/6]
      chance: 20
    '1452399689067':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1548
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/jockey.png[2/6]
      chance: 20
    '1452399692558':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1549
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/jockey.png[3/6]
      chance: 20
    '1452399696120':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1550
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/jockey.png[4/6]
      chance: 20
    '1452399704264':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1551
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/jockey.png[5/6]
      chance: 15
    '1452399710117':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1552
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/jockey.png[6/6]
      chance: 10
enderheart:
  map-id: 1560
  items:
    '1452400483286':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1554
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/enderheart.png[1/6]
      chance: 10
    '1452400489937':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1555
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/enderheart.png[2/6]
      chance: 15
    '1452400495737':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1556
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/enderheart.png[3/6]
      chance: 20
    '1452400499162':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1557
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/enderheart.png[4/6]
      chance: 20
    '1452400502012':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1558
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/enderheart.png[5/6]
      chance: 20
    '1452400504962':
      itemstack:
        ==: org.bukkit.inventory.ItemStack
        type: MAP
        damage: 1559
        meta:
          ==: ItemMeta
          meta-type: MAP
          display-name: mc/enderheart.png[6/6]
      chance: 20
