usingConfig: true
config-version: 3
tabmenu:
  enabled: true
  header: animation:swedecraft
  footer: animation:bottom
welcome_message:
  enabled: true
  title: '&5Välkommen tillbaka {PLAYER}!'
  subtitle: '&dHjälp gärna vår server!'
  fadeIn: -1
  stay: -1
  fadeOut: -1
  first-join:
    title: '&5Välkommen till SwedeCraft {PLAYER}'
    subtitle: '&dHoppas du kommer ha roligt!'
number-format:
  enabled: true
  format: '#,###.##'
date-format:
  format: EEE, dd MMM yyyy HH:mm:ss z
actionbar-welcome:
  enabled: true
  message: '&a&lWelcome!'
  first-join:
    message: '&2&lWelcome It''s your first time!'
using-bungeecord: false
disabled-variables:
- my-disabled-variable
- also-called-placeholders
legacy-client-support: false
updater:
  check-automatically: false
