name: TitleManager
version: 1.5.11
author: Puharesource

main: io.puharesource.mc.titlemanager.TitleManager
softdepend: [Vault, Essentials, VanishNoPacket, EZRanksLite, PlaceholderAPI, SuperVanish, PremiumVanish]

commands:
  tm:
    description: TitleManager commands.
    usage: /tm
    aliases: [titlemanager]