name: DeluxeTags
main: me.clip.deluxetags.DeluxeTags
version: 1.7.1
author: extended_clip
description: DeluxeChat add on to allow players to select a custom tag
commands:
   tags:
     description: DeluxeTags command
permissions:
    deluxetags.gui:
        description: ability to select a tag from gui
        default: op
    deluxetags.select:
        description: ability to select a tag by command
        default: op
    deluxetags.list:
        description: ability to view own tags
        default: op
    deluxetags.list.all:
        description: ability to view all loaded tags
        default: op
    deluxetags.list.player:
        description: ability to view all loaded tags
        default: op
    deluxetags.set:
        description: ability to set a players tag
        default: op
    deluxetags.clear:
        description: ability to clear a players active tag
        default: op
    deluxetags.create:
        description: ability to create a tag by command
        default: op
    deluxetags.delete:
        description: ability to delete a tag by command
        default: op
    deluxetags.setdescription:
        description: ability to set a tags description by command
        default: op
    deluxetags.reload:
        description: ability to reload the plugin
        default: op